export const UPPER_BAR_PADDING = 80
export const UPPER_BAR_HEIGHT = 77

export const SIDE_BAR_MENU_BACKGROUND_COLOR = '$whiteSmoke'
export const SIDE_BAR_MENU_OPTIONS_ICONS_SIZE = 25
export const SIDE_BAR_MENU_OPTIONS_HEIGHT = 50
export const SIDE_BAR_MENU_OPTIONS_PADDING = 11
export const SIDE_BAR_MENU_OPTIONS_HOVER_BACKGROUND_COLOR = '$silver'
export const SIDE_BAR_MENU_OPTIONS_HOVER_TRANSITION = '.3s'
export const SIDE_BAR_MENU_OPTIONS_ACTIVE_BACKGROUND_COLOR = '$timberWolf'
export const SIDE_BAR_MENU_OPTIONS_SELECTED_BACKGROUND_COLOR = '$antiFlashWhite'

export const USER_INFO_FORM_TEXT_AREA_WIDTH = 840
export const USER_INFO_FORM_INPUT_WIDTH = 400
export const USER_INFO_FORM_JOB_FUNCTION_SELECT_WIDTH =
    USER_INFO_FORM_INPUT_WIDTH - 10

export const AIRCRAFT_FORM_LARGE_INPUT_WIDTH = 300
